FROM node:8.8.1-alpine
LABEL name="Surfline Project API Container"
LABEL version="1.0"

# Setup working directory for the server container
RUN mkdir /server
WORKDIR /server

# Copy server files over and install dependencies
COPY ./server/ ./

# Install dependencies for rebuilding bcrypt, then run npm install, then rebuild bcrypt
# This avoids a segmentation fault when using the alpine node image
# Reference: https://github.com/kelektiv/node.bcrypt.js/issues/528
RUN apk --no-cache add --virtual build-deps build-base python
RUN npm install
RUN npm rebuild bcrypt --build-from-source

EXPOSE 3006
EXPOSE 5858
CMD ["npm", "run", "start:server:dev"]