version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BABEL_ENV=production
    ports:
      - "80:80"
    env_file:
      - ./prod.env
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ../server/mongo/:/data/db
    ports:
      - "27017:27017"